USE master
GO

CREATE DATABASE [{{DBNAME}}]
GO

ALTER DATABASE [{{DBNAME}}] MODIFY FILE ( NAME = N'{{DBNAME}}', SIZE = {{DATASIZE}}KB , FILEGROWTH = {{DATAGROWTH}}KB )
GO
ALTER DATABASE [{{DBNAME}}] MODIFY FILE ( NAME = N'{{DBNAME}}_log', SIZE = {{LOGSIZE}}KB , MAXSIZE = UNLIMITED, FILEGROWTH = {{LOGGROWTH}}KB )
GO
ALTER DATABASE [{{DBNAME}}] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [{{DBNAME}}] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET ARITHABORT OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [{{DBNAME}}] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [{{DBNAME}}] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [{{DBNAME}}] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET  DISABLE_BROKER 
GO
ALTER DATABASE [{{DBNAME}}] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [{{DBNAME}}] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [{{DBNAME}}] SET  READ_WRITE 
GO
ALTER DATABASE [{{DBNAME}}] SET RECOVERY {{RECOVERY}} 
GO
ALTER DATABASE [{{DBNAME}}] SET  MULTI_USER 
GO
ALTER DATABASE [{{DBNAME}}] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [{{DBNAME}}] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [{{DBNAME}}] SET DELAYED_DURABILITY = DISABLED 
GO
USE [{{DBNAME}}]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [{{DBNAME}}] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
