//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasfCli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasfCli.SqlFiles", typeof(SqlFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACKUP DATABASE [{{DBNAME}}] TO  
        ///	DISK = N&apos; {{BACKUPFILENAME}}&apos; 
        ///	WITH  
        ///		FORMAT, 
        ///		INIT,  
        ///		SKIP, 
        ///		NOREWIND, 
        ///		NOUNLOAD.
        /// </summary>
        internal static string BackupDb {
            get {
                return ResourceManager.GetString("BackupDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE master
        ///GO
        ///
        ///CREATE DATABASE [{{DBNAME}}]
        ///GO
        ///
        ///ALTER DATABASE [{{DBNAME}}] MODIFY FILE ( NAME = N&apos;{{DBNAME}}&apos;, SIZE = {{DATASIZE}}KB , FILEGROWTH = {{DATAGROWTH}}KB )
        ///GO
        ///ALTER DATABASE [{{DBNAME}}] MODIFY FILE ( NAME = N&apos;{{DBNAME}}_log&apos;, SIZE = {{LOGSIZE}}KB , MAXSIZE = UNLIMITED, FILEGROWTH = {{LOGGROWTH}}KB )
        ///GO
        ///ALTER DATABASE [{{DBNAME}}] SET COMPATIBILITY_LEVEL = 100
        ///GO
        ///ALTER DATABASE [{{DBNAME}}] SET ANSI_NULL_DEFAULT OFF 
        ///GO
        ///ALTER DATABASE [{{DBNAME}}] SET ANSI_NULLS OFF 
        ///GO
        ///ALTER DAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF (DB_ID(&apos;{0}&apos;) IS NOT NULL) BEGIN
        ///	SELECT CAST(1 AS BIT)
        ///END ELSE BEGIN
        ///	SELECT CAST(0 AS BIT)
        ///END
        ///.
        /// </summary>
        internal static string DbExists {
            get {
                return ResourceManager.GetString("DbExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF (OBJECT_ID(&apos;{0}&apos;) IS NOT NULL) BEGIN
        ///	SELECT CAST(1 AS BIT)
        ///END ELSE BEGIN
        ///	SELECT CAST(0 AS BIT)
        ///END
        ///.
        /// </summary>
        internal static string ObjectExists {
            get {
                return ResourceManager.GetString("ObjectExists", resourceCulture);
            }
        }
    }
}
